export {default as AdminDashboard} from './AdminDashboard/index'
export {default as CreatePost} from './CreatePost/index'
export {default as Home} from './Home/index'
export {default as Login} from './Login/index'
export {default as PostDetail} from './PostDetail/index'
export {default as Register} from './Register/index'
export {default as UserProfile} from './UserProfile/index'
